name: shebuilds
favicon: null
layout_spectrum: 0.5582524426281452
typography_spectrum: 0.5553638234268874
title: Home Improvement Community for Women
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#59227f'
    - '#f1592a'
    - '#7b4d96'
    - '#b69dc8'
  brandStrength: 0.1875
  lightness: 0.13729985314421356
  saturation: 0.7150267155375332
  rhythmicContrast: 0.7360678799450397
purpose: []
